language: python
python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_script:
  - pip install --upgrade pip
  - pip install codecov
  - pip install coveralls
  
script: nosetests --no-skip --with-coverage
